# Generated by Django 4.1.2 on 2022-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
