# Generated by Django 4.1.2 on 2022-11-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0004_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyperson', models.CharField(max_length=255)),
                ('keypersonrole', models.CharField(max_length=255)),
                ('keypersonresponsibilities', models.CharField(max_length=255)),
            ],
        ),
    ]
