# Generated by Django 4.1.2 on 2022-11-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0005_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productserviceoffer', models.CharField(max_length=255)),
                ('targetcustomers', models.CharField(max_length=255)),
                ('geographicmarket', models.CharField(max_length=255)),
                ('competitiveadvantage', models.CharField(max_length=255)),
            ],
        ),
    ]
