# Generated by Django 4.1.2 on 2022-11-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0006_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.CharField(max_length=255)),
                ('competitorweakness', models.CharField(max_length=255)),
                ('competitiveadvantages', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencysymbol', models.CharField(max_length=255)),
                ('planstartyear', models.IntegerField()),
                ('salesunitfreqperday', models.IntegerField()),
                ('salesunitprice', models.IntegerField()),
                ('salesperday', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salesgrowthpercent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cosofsales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bankexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciationexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employeeexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insuranceexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marketingexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('officeexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('otherexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premisesexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professionaexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shippingexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travelexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilityexpensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expensesyearone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expensesgrowthpercent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customerdayscredit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplierdayscredit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equitycashinjection', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategicstep', models.CharField(max_length=255)),
                ('methodofselling', models.CharField(max_length=255)),
                ('advertising', models.CharField(max_length=255)),
            ],
        ),
    ]
